# Generated by Django 2.2.12 on 2021-06-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_experience_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50, verbose_name='time_work')),
                ('title', models.CharField(max_length=50, verbose_name='Works_experience')),
            ],
            options={
                'verbose_name': 'Work_experience',
                'verbose_name_plural': 'Works_experience',
            },
        ),
    ]
