# Generated by Django 2.2.12 on 2021-06-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_work_experience_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50, verbose_name='time_work')),
                ('location', models.CharField(max_length=50, verbose_name='Works_experience')),
                ('title', models.CharField(max_length=100, verbose_name='Works_experience')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
            },
        ),
        migrations.AlterField(
            model_name='work_experience_description',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Works_experience'),
        ),
    ]
