# Generated by Django 2.2.12 on 2021-06-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210616_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='education_description',
            name='logo',
            field=models.ImageField(default='', upload_to='main/', verbose_name='Logo'),
            preserve_default=False,
        ),
    ]
