# Generated by Django 2.2.12 on 2021-06-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_education_description_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education_description',
            name='logo',
        ),
        migrations.AlterField(
            model_name='education_description',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Works_experience'),
        ),
    ]
